FROM alpine:3.20

RUN apk add --no-cache openssh-server openssh-sftp-server && \
    ssh-keygen -t ecdsa -b 256 -f /etc/ssh/ssh_host_ecdsa_key -N "" && \
    ssh-keygen -t rsa   -b 2048 -f /etc/ssh/ssh_host_rsa_key   -N "" && \
    rm -f /etc/ssh/ssh_host_ed25519_key /etc/ssh/ssh_host_dsa_key && \
    adduser -D -s /bin/sh russh_test && \
    echo "russh_test:russh_test" | chpasswd

COPY sshd_config_test /etc/ssh/sshd_config

EXPOSE 2200

CMD ["/usr/sbin/sshd", "-D", "-e"]
